# Copie ce fichier dans .streamlit/secrets.toml
# et remplace par tes vraies clés Supabase

SUPABASE_URL = "https://rhazrrjmmqtttdwrnhsy.supabase.co"
SUPABASE_KEY = "sb_publishable_LQT9P4Yrtcib0mXhVSdGlw_DkozsGEJ"
